### ISSUE TITLE
No voice with any of the voice files

### ISSUE THREAD

**Issue by kinnerful** [BGforgeNet/Fallout2_Cassidy_Head#3]
Added this mod half-way (after recruiting Cassidy) during my UPU game. Cassidy's head shows up nicely, but none of the voice files can make him talk when I click him.

**Comment by burner1024** [comment]
Yes, the support for it was included after latest UPU release.
Drop [that file](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/dialog/vccasidy.msg) into `data/text/english/dialog`, that should fix it.
